name: Deploy demo

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Do nothing (just needs to be green)
        run: echo "Building... done."

  deploy:
    name: Deploy to stg
    needs: build
    runs-on: ubuntu-latest
    environment: stg
    steps:
      - name: Deploy
        run: echo "Deploying to stg..."
